apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: pod-csr.web
spec:
 groups:
 - system:authenticated
 request: $(cat server.csr | base 64 | tr -d '\n')
 usages:
 - digital signature
 - key encipherment
 - server auth

