apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: asg-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testapp
  minReplicas: 3
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
