apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: testapp
  replicas: 3
  minReadySeconds: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: nginx
        image: ibiliaze/engine4:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 0.2
        livenessProbe:
          exec:
            command:
            - echo
            - testing
          initialDelaySeconds: 5
          periodSeconds: 5
