apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ssd
  capacity:
    storage: 20Gi
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDoisk:
    pdName: uber-disk
