apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ssd
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  gcePersistentDisk:
    name: test-disk
