apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: nginx
    name: nginx
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    securityContext:
      runAsUser: 2000 #user ID
        fsGroup: 3000 #group ID
    volumeMounts:
    - name: message-volume
      mountPath: /message
  volumes:
  - name: message-volume
    hostPath:
      path: /etc/message
