apiVersion: v1
kind: Pod
metadata:
  name: manycontainers
spec:
  securityContext:
    fsGroup: 555
    supplementalGroups:
    - 666
    - 777
  containers:
  - image: nginx
    name: first
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    securityContext:
      runAsUser: 1111
    volumeMounts:
    - name: my-volume  
      mountPath: /volume #directory will be owned by the group 555
  - image: nginx
    name: second
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    securityContext:
      runAsUser: 2222
    volumeMounts:
    - name: my-volume
      mountPath: /volume #directory will be owned by the group 555

  volumes:
  - name: my-volume
    emptyDir: {}
