apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  securityContext:
    capabilities:
      add: ["NET_ADMIN", "SYS_TIME"]
  containers:
  - image: ubuntu:latest
    name: ubuntu:ctr
    command:
    - /bin/bash
    - "-c"
    - "cat /message/message.txt"
    - "sleep 60m"
    volumeMounts:
    - name: message-volume
      mountPath: /message
  volumes:
  - name: message-volume
    hostPath:
      path: /etc/message
