apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    name: node
spec:
  selector:
    matchLabels:
      name: mypod
  replicas: 1
  template:
    metadata:
      labels:
        name: mypod
    spec:
      containers:
        - image: ibiliaze/dmvpn1:latest
          name: dmvpn
          ports:
          - containerPort: 5000
