apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  SENDGRID_API_KEY: U0RsSE1XLVJjMjAxdkdOSy1mbTlRLmFXOG45ek9wWkt5cld2ekQ2Nkt4RTRuc1NDVk5YTkYzN0hWc0xhbTgyWW8=
  JWT_SECRET: NENBN0UyRUFGOThFRDQ5N0UwREJGMjAxNENFODcwOTU3RTQxMjIwNTA2NTlEOTY0Rjk4RUY1NkI1ODE5OUQ3NQ==
  MONGODB_PASSWORD: ZzUydW5aYkZRdkh5UkEyZw==

