apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfig
resources:
- resources:
  - secrets
  providers:
  - aescbc:
      keys:
      - name: key1
        secret: N+s3sGJE1S61cqYyLoN3Vg==
  - identity: {}
