apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:25'
      smtp_from: 'alertmanager@myorg.org'
      smtp_require_tls: false
    route:
      receiver: slack_receiver
    receivers:
    - name: slack_receiver
      slack_configs:
      - send_resolved: true
        username: 'Ibi'
        api_url: 'https://hooks.slack.com/services/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'
        channel: '#prometheus-alerts'
