apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: nginx:latest
    name: nginx
    command:
    - /bin/bash
    - "-c"
    - 'echo "this is my random error message" > /var/termination-reason ; exit 1'
    terminationMessagePath: /var/termination-reason
