apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dnsp
spec:
  serviceAccountName: testsa
  containers:
  - image: nginx:latest
    name: dnsi
    command:
    - sleep 
    - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

