apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: ClusterIP
  ClusterIP: 10.8.0.50
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: hello-world
