apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnodes
  labels:
    app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: ibiliaze/engine2:latest
        name: engine
        ports:
         - containerPort: 80
        command:
         - /bin/bash
         - "-c"
         - "sleep 60m"
         - "service nginx start"
        #imagePullPolicy: IfNotPresent
      restartPolicy: Always
